service: bmes-express

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-west-2
  memorySize: 512
  timeout: 10

iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            # Allow the Express app to write and read from DynamoDB
            - "dynamodb:PutItem" # Save ESP32 data
            - "dynamodb:GetItem" # Fetch Data
            - "dynamodb:Scan" # Accesses Items in the table
            - "dynamodb:Query" # Retrieve Items from a query
          Resource: 
            # Restrict access to ONLY our specific table
            - "arn:aws:dynamodb:${self:provider.region}:*:table/esp32-readings-table"

functions:
  app:
    handler: index.handler
    events: 
      - httpApi: '*'

# https://www.serverless.com/plugins/serverless-better-credentials

plugins:
  - serverless-better-credentials # as the first plugin
  # - ... other plugins

custom:
  betterCredentials:
    # Use this flag to turn off the plugin entirely, which you may want for certain stages.
    # Defaults to true.
    enabled: true
